# Generated by Django 6.0 on 2026-02-19 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_medicineschedule_next_reminder_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicineReminder',
        ),
    ]
