# Generated by Django 5.2.3 on 2026-02-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
