# Generated by Django 5.2.3 on 2026-02-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_bloodrequest_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
